fix: crop image on resize to cover full square
guyfedwards/emojo pull request #20
Opened 2018-11-21 20:17 UTC by guyfedwards

2018-11-21 21:26 UTC, benswinburne requested changes

2018-11-21 21:26 UTC, benswinburne commented on src/utils.js
> -        fit: sharp.fit.inside,
Suggest leaving `fit: sharp.fit.cover,` in so it's quick to read what it's doing when reading the code rather than having to know the default/go look it up.

2018-11-21 21:26 UTC, benswinburne commented on src/utils.js
>      ? new Gifsicle(['--resize-fit', '128'])
Need to make Gifsicle do the same?

2018-12-14 22:40 UTC, guyfedwards commented on src/utils.js
>      ? new Gifsicle(['--resize-fit', '128'])
https://github.com/guyfedwards/emojo/issues/21

2018-12-14 22:40 UTC, benswinburne approved these changes

2018-12-14 22:56 UTC, merged